name: White Box Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  white-box-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: |
        pip install -r requirements.txt
        coverage run --branch -m pytest
        coverage report -m
        coverage xml
    - uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
